const AdmZip = require('adm-zip');
const fs = require('fs');
const path = require('path');

const TEXT_EXTENSIONS = new Set([
  '.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.py', '.rb', '.java',
  '.kt', '.go', '.rs', '.c', '.cpp', '.h', '.hpp', '.cs', '.swift',
  '.dart', '.lua', '.php', '.sh', '.ps1', '.html', '.htm', '.css',
  '.scss', '.sass', '.less', '.vue', '.svelte', '.astro', '.json',
  '.xml', '.yaml', '.yml', '.toml', '.ini', '.cfg', '.conf', '.md',
  '.txt', '.markdown', '.sql', '.graphql', '.prisma', '.dockerfile',
  '.gitignore', '.eslintrc', '.prettierrc', '.env', '.env.example'
]);

function isTextFile(filePath, buffer) {
  const ext = path.extname(filePath).toLowerCase();
  if (TEXT_EXTENSIONS.has(ext)) return true;
  if (buffer) {
    for (let i = 0; i < Math.min(buffer.length, 1024); i++) {
      if (buffer[i] === 0) return false;
    }
    return true;
  }
  return false;
}

const getPriority = (filename) => {
  const name = filename.toLowerCase();
  if (name.includes('app.') || name.includes('index.') || name.includes('main.')) return 10;
  if (name.includes('controller') || name.includes('route')) return 8;
  if (name.includes('component')) return 7;
  if (name.includes('util') || name.includes('helper')) return 5;
  if (name.includes('config')) return 3;
  return 1;
};

async function processZipFile(zipPath, fixedFiles = []) {
  const zip = new AdmZip(zipPath);
  const zipEntries = zip.getEntries();
  const codebase = [];

  // Apply fixes if any
  if (fixedFiles.length > 0) {
    fixedFiles.forEach(fix => {
      const entry = zip.getEntry(fix.file);
      if (entry) {
        zip.updateFile(fix.file, Buffer.from(fix.content, 'utf8'));
      } else {
        zip.addFile(fix.file, Buffer.from(fix.content, 'utf8'));
      }
    });
    return { zipBuffer: zip.toBuffer() };
  }

  // Read for AI Context
  zipEntries.forEach(entry => {
    if (entry.isDirectory) return;
    if (entry.entryName.includes('node_modules/') || entry.entryName.includes('.git/') || entry.entryName.includes('.next/')) return;

    const buffer = entry.getData();
    const isText = isTextFile(entry.entryName, buffer);
    let skipAI = true;
    let content = null;

    if (isText && buffer.length < 150000) {
      content = buffer.toString('utf8');
      skipAI = false;
    }

    codebase.push({
      path: entry.entryName,
      content: content,
      skipAI: skipAI
    });
  });

  const filesForAI = codebase.filter(f => !f.skipAI);
  filesForAI.sort((a, b) => getPriority(b.path) - getPriority(a.path));

  return {
    filesForAI: filesForAI.slice(0, 20),
    zipBuffer: zip.toBuffer()
  };
}

async function processDirectFiles(multerFiles, fixedFiles = []) {
  const zip = new AdmZip();
  const codebase = [];

  // If we are just rebuilding the ZIP with fixes
  if (fixedFiles.length > 0) {
    // First add all original files
    multerFiles.forEach(file => {
      const fix = fixedFiles.find(f => f.file === file.originalname);
      const content = fix ? Buffer.from(fix.content, 'utf8') : fs.readFileSync(file.path);
      zip.addFile(file.originalname, content);
    });
    // Add any NEW files generated by AI that weren't in original
    fixedFiles.forEach(fix => {
      if (!multerFiles.find(f => f.originalname === fix.file)) {
        zip.addFile(fix.file, Buffer.from(fix.content, 'utf8'));
      }
    });
    return { zipBuffer: zip.toBuffer() };
  }

  // Normal processing for AI context
  multerFiles.forEach(file => {
    const buffer = fs.readFileSync(file.path);
    const isText = isTextFile(file.originalname, buffer);
    let content = null;
    let skipAI = true;

    if (isText && buffer.length < 100000) {
      content = buffer.toString('utf8');
      skipAI = false;
    }

    zip.addFile(file.originalname, buffer);
    codebase.push({
      path: file.originalname,
      content: content,
      skipAI: skipAI
    });
  });

  const filesForAI = codebase.filter(f => !f.skipAI);
  filesForAI.sort((a, b) => getPriority(b.path) - getPriority(a.path));

  return {
    filesForAI: filesForAI.slice(0, 20),
    zipBuffer: zip.toBuffer()
  };
}

module.exports = { processZipFile, processDirectFiles };
